spring.application.name=go-work

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gowork}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT:5000}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

storage.path=${STORAGE_PATH:D:\tmp}

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

app.base-url=${APP_BASE_URL:http://localhost:8080}
