spring.application.name=go-work
spring.datasource.url=jdbc:postgresql://localhost:5432/gowork
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

storage.path = D:\\